#This is the configuration file for the Assetto Corsa Gym environment.
task: AssettoCorsaGym
seed: 0

#Environmnet Parameters: Taken from ASsetto Corsa Gym, all parameters are required to use the environment.
AssettoCorsa:
  ego_sampling_freq: 25           #In Hz, so 25 means that the environment is running at 25 frames per second
  max_episode_py_time: 600.       #In seconds, so 10 minutes
  gap_const: 12.
  eval_number_of_laps: 4          #Includes the out lap, so 3 actual laps
  save_lap_csv: False
  remote_machine_ip: "localhost"
  ego_server_port: 2345
  opponents_server_port: 2346
  simulation_management_server_port: 2347
  use_relative_actions: True
  enable_sensors: True
  vjoy_executed_by_server: False
  enable_out_of_track_termination: True
  enable_low_speed_termination: True
  recover_car_on_done: False
  send_reset_at_start: True
  record_controls_from_client: False
  enable_out_of_track_penalty: False
  max_laps_number: null
  enable_task_id_in_obs: False
  penalize_actions_diff: False
  penalize_actions_diff_coef: 0.1
  max_steer_rate: 900.0           #Steering in deg/s
  track: "monza"                  #Track name, should be one of the tracks available in Assetto Corsa
  car: "bmw_z4_gt3"
  use_ac_out_of_track: True
  add_previous_obs_to_state: True
  use_reference_line_in_reward: True
  use_target_speed: False
  screen_capture_enable: False

  #This should be a multiple of the resolution set in Assetto Corsa (Mine is currently at 640x480)
  final_image_width: 320
  final_image_height: 240
  color_mode: "gray"
  use_obs_extra: False

  # Training Run Parameters
train:
  total_timesteps: 1000000
  device: "cuda"  # or "cpu"
  save_path: "./models/sac_assetto_corsa"
  log_interval: 10  # How often to print progress

  # SAC Agent Hyperparameters (Stable-Baselines3)
sac:
  learning_rate: 0.0003
  buffer_size: 1000000
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  train_freq: 1
  gradient_steps: 1
  learning_starts: 10000

# Evaluation Parameters
eval:
  n_eval_episodes: 5
  eval_freq: 50000 # Evaluate every X steps

# Policy Architecture (easier to update, will be used in the agent init method)
  policy_kwargs:
    net_arch: [256, 256]
    use_sde: False # State Dependent Exploration